global:
  scrape_interval: 15s
  evaluation_interval: 15s
  # scrape_timeout is set to the global default (10s).

# A list of scrape configurations.
scrape_configs:
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "operator"
    scrape_interval: 5s
    static_configs:
      - targets: ["operator:5000"]

rule_files:
  - "/etc/prometheus/rules/*"

alerting:
 alertmanagers:
   - static_configs:
     - targets:
       - alertmanager:9093