{
 "title": "GrowBox 420 Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "From Phase Beginning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "growbox_phase_from_start_seconds"
    }
   ]
  },
  {
   "title": "Current Phase",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "growbox_phase_name == 1", "legendFormat": "{{ growbox_phase_name }}" }
   ]
  },
  {
   "title": "Until Phase End",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "growbox_phase_before_finish_seconds"
    }
   ]
  },
  {
   "title": "From Mode Beginning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "growbox_light_dark_mode_from_start_seconds"
    }
   ]
  },
  {
   "title": "Current Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "growbox_light_dark_mode == 1", "legendFormat": "{{ growbox_light_dark_mode }}" }
   ]
  },
  {
   "title": "Until Mode End",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "growbox_light_dark_mode_before_finish_seconds"
    }
   ]
  },
  {
   "title": "Day/Night",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    { "expr": "growbox_light_dark_mode", "legendFormat": "{{growbox_light_dark_mode}}" }
   ]
  },
  {
   "title": "FAN",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "growbox_fan_enabled" }
   ]
  },
  {
   "title": "Light",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "growbox_light_enabled" }
   ]
  },
  {
   "title": "Water",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "growbox_water_enabled" }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "growbox_temperature_celsius" }
   ]
  },
  {
   "title": "Humudity",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "growbox_humidity_percents" }
   ]
  },
  {
   "title": "Moisture",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "growbox_moisture_percents" }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    { "expr": "growbox_temperature_celsius", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Humudity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    { "expr": "growbox_humidity_percents", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Moisture",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "growbox_moisture_percents", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "All Alerts Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  }
 ]
}